"""Extra setting definitions — security, storage, user, and memory settings."""

from __future__ import annotations

from src.kernel.schemas.setting import SettingCategory, SettingType

EXTRA_SETTING_DEFINITIONS: dict[str, dict] = {
    # ============================================
    # JWT Authentication Settings
    # ============================================
    "JWT_ALGORITHM": {
        "type": SettingType.STRING,
        "category": SettingCategory.SECURITY,
        "subcategory": "jwt",
        "description": "settingDesc.JWT_ALGORITHM",
        "default": "HS256",
    },
    "ACCESS_TOKEN_EXPIRE_HOURS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SECURITY,
        "subcategory": "jwt",
        "description": "settingDesc.ACCESS_TOKEN_EXPIRE_HOURS",
        "default": 24,
    },
    "REFRESH_TOKEN_EXPIRE_DAYS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SECURITY,
        "subcategory": "jwt",
        "description": "settingDesc.REFRESH_TOKEN_EXPIRE_DAYS",
        "default": 7,
    },
    # ============================================
    # Email Settings (Resend)
    # ============================================
    "EMAIL_ENABLED": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.EMAIL,
        "subcategory": "general",
        "description": "settingDesc.EMAIL_ENABLED",
        "default": False,
        "frontend_visible": True,
    },
    "REQUIRE_EMAIL_VERIFICATION": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.EMAIL,
        "subcategory": "general",
        "description": "settingDesc.REQUIRE_EMAIL_VERIFICATION",
        "default": False,
        "depends_on": "EMAIL_ENABLED",
        "frontend_visible": True,
    },
    "PASSWORD_RESET_EXPIRE_HOURS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.EMAIL,
        "subcategory": "general",
        "description": "settingDesc.PASSWORD_RESET_EXPIRE_HOURS",
        "default": 24,
        "depends_on": "EMAIL_ENABLED",
    },
    # ============================================
    # Cloudflare Turnstile (CAPTCHA) Settings
    # ============================================
    "TURNSTILE_ENABLED": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.CAPTCHA,
        "subcategory": "turnstile",
        "description": "settingDesc.TURNSTILE_ENABLED",
        "default": False,
        "frontend_visible": True,
    },
    "TURNSTILE_SITE_KEY": {
        "type": SettingType.STRING,
        "category": SettingCategory.CAPTCHA,
        "subcategory": "turnstile",
        "description": "settingDesc.TURNSTILE_SITE_KEY",
        "default": "",
        "depends_on": "TURNSTILE_ENABLED",
        "frontend_visible": True,
    },
    "TURNSTILE_SECRET_KEY": {
        "type": SettingType.STRING,
        "category": SettingCategory.CAPTCHA,
        "subcategory": "turnstile",
        "description": "settingDesc.TURNSTILE_SECRET_KEY",
        "default": "",
        "depends_on": "TURNSTILE_ENABLED",
        "is_sensitive": True,
    },
    "TURNSTILE_REQUIRE_ON_LOGIN": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.CAPTCHA,
        "subcategory": "turnstile",
        "description": "settingDesc.TURNSTILE_REQUIRE_ON_LOGIN",
        "default": False,
        "depends_on": "TURNSTILE_ENABLED",
        "frontend_visible": True,
    },
    "TURNSTILE_REQUIRE_ON_REGISTER": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.CAPTCHA,
        "subcategory": "turnstile",
        "description": "settingDesc.TURNSTILE_REQUIRE_ON_REGISTER",
        "default": True,
        "depends_on": "TURNSTILE_ENABLED",
        "frontend_visible": True,
    },
    "TURNSTILE_REQUIRE_ON_PASSWORD_CHANGE": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.CAPTCHA,
        "subcategory": "turnstile",
        "description": "settingDesc.TURNSTILE_REQUIRE_ON_PASSWORD_CHANGE",
        "default": True,
        "depends_on": "TURNSTILE_ENABLED",
        "frontend_visible": True,
    },
    # ============================================
    # S3 Storage Settings
    # ============================================
    "S3_ENABLED": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.S3,
        "subcategory": "connection",
        "description": "settingDesc.S3_ENABLED",
        "default": False,
        "frontend_visible": True,
    },
    "S3_PROVIDER": {
        "type": SettingType.SELECT,
        "category": SettingCategory.S3,
        "subcategory": "connection",
        "description": "settingDesc.S3_PROVIDER",
        "default": "aws",
        "depends_on": "S3_ENABLED",
        "options": ["aws", "aliyun", "tencent", "minio", "custom"],
    },
    "S3_ENDPOINT_URL": {
        "type": SettingType.STRING,
        "category": SettingCategory.S3,
        "subcategory": "connection",
        "description": "settingDesc.S3_ENDPOINT_URL",
        "default": "",
        "depends_on": "S3_ENABLED",
    },
    "S3_ACCESS_KEY": {
        "type": SettingType.STRING,
        "category": SettingCategory.S3,
        "subcategory": "connection",
        "description": "settingDesc.S3_ACCESS_KEY",
        "default": "",
        "is_sensitive": True,
        "depends_on": "S3_ENABLED",
    },
    "S3_SECRET_KEY": {
        "type": SettingType.STRING,
        "category": SettingCategory.S3,
        "subcategory": "connection",
        "description": "settingDesc.S3_SECRET_KEY",
        "default": "",
        "is_sensitive": True,
        "depends_on": "S3_ENABLED",
    },
    "S3_REGION": {
        "type": SettingType.STRING,
        "category": SettingCategory.S3,
        "subcategory": "connection",
        "description": "settingDesc.S3_REGION",
        "default": "us-east-1",
        "depends_on": "S3_ENABLED",
    },
    "S3_BUCKET_NAME": {
        "type": SettingType.STRING,
        "category": SettingCategory.S3,
        "subcategory": "bucket",
        "description": "settingDesc.S3_BUCKET_NAME",
        "default": "",
        "depends_on": "S3_ENABLED",
    },
    "S3_CUSTOM_DOMAIN": {
        "type": SettingType.STRING,
        "category": SettingCategory.S3,
        "subcategory": "bucket",
        "description": "settingDesc.S3_CUSTOM_DOMAIN",
        "default": "",
        "depends_on": "S3_ENABLED",
    },
    "S3_PATH_STYLE": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.S3,
        "subcategory": "bucket",
        "description": "settingDesc.S3_PATH_STYLE",
        "default": False,
        "depends_on": "S3_ENABLED",
    },
    "S3_PUBLIC_BUCKET": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.S3,
        "subcategory": "bucket",
        "description": "settingDesc.S3_PUBLIC_BUCKET",
        "default": False,
        "depends_on": "S3_ENABLED",
    },
    "S3_MAX_FILE_SIZE": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.S3,
        "subcategory": "limits",
        "description": "settingDesc.S3_MAX_FILE_SIZE",
        "default": 10485760,
        "depends_on": "S3_ENABLED",
    },
    "S3_INTERNAL_UPLOAD_MAX_SIZE": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.S3,
        "subcategory": "limits",
        "description": "settingDesc.S3_INTERNAL_UPLOAD_MAX_SIZE",
        "default": 52428800,
        "depends_on": "S3_ENABLED",
    },
    "S3_PRESIGNED_URL_EXPIRES": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.S3,
        "subcategory": "limits",
        "description": "settingDesc.S3_PRESIGNED_URL_EXPIRES",
        "default": 604800,
        "depends_on": "S3_ENABLED",
    },
    # ============================================
    # File Upload Limits
    # ============================================
    "LOCAL_STORAGE_PATH": {
        "type": SettingType.STRING,
        "category": SettingCategory.FILE_UPLOAD,
        "subcategory": "storage",
        "description": "settingDesc.LOCAL_STORAGE_PATH",
        "default": "./uploads",
    },
    "FILE_UPLOAD_MAX_SIZE_IMAGE": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.FILE_UPLOAD,
        "subcategory": "limits",
        "description": "settingDesc.FILE_UPLOAD_MAX_SIZE_IMAGE",
        "default": 10,
    },
    "FILE_UPLOAD_MAX_SIZE_VIDEO": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.FILE_UPLOAD,
        "subcategory": "limits",
        "description": "settingDesc.FILE_UPLOAD_MAX_SIZE_VIDEO",
        "default": 100,
    },
    "FILE_UPLOAD_MAX_SIZE_AUDIO": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.FILE_UPLOAD,
        "subcategory": "limits",
        "description": "settingDesc.FILE_UPLOAD_MAX_SIZE_AUDIO",
        "default": 50,
    },
    "FILE_UPLOAD_MAX_SIZE_DOCUMENT": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.FILE_UPLOAD,
        "subcategory": "limits",
        "description": "settingDesc.FILE_UPLOAD_MAX_SIZE_DOCUMENT",
        "default": 50,
    },
    "FILE_UPLOAD_MAX_FILES": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.FILE_UPLOAD,
        "subcategory": "limits",
        "description": "settingDesc.FILE_UPLOAD_MAX_FILES",
        "default": 10,
    },
    # ============================================
    # Long-term Storage Settings (PostgreSQL)
    # ============================================
    "ENABLE_POSTGRES_STORAGE": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.LONG_TERM_STORAGE,
        "subcategory": "connection",
        "description": "settingDesc.ENABLE_POSTGRES_STORAGE",
        "default": False,
        "frontend_visible": True,
    },
    "POSTGRES_HOST": {
        "type": SettingType.STRING,
        "category": SettingCategory.LONG_TERM_STORAGE,
        "subcategory": "connection",
        "description": "settingDesc.POSTGRES_HOST",
        "default": "localhost",
        "depends_on": "ENABLE_POSTGRES_STORAGE",
    },
    "POSTGRES_PORT": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.LONG_TERM_STORAGE,
        "subcategory": "connection",
        "description": "settingDesc.POSTGRES_PORT",
        "default": 5432,
        "depends_on": "ENABLE_POSTGRES_STORAGE",
    },
    "POSTGRES_USER": {
        "type": SettingType.STRING,
        "category": SettingCategory.LONG_TERM_STORAGE,
        "subcategory": "connection",
        "description": "settingDesc.POSTGRES_USER",
        "default": "postgres",
        "depends_on": "ENABLE_POSTGRES_STORAGE",
    },
    "POSTGRES_PASSWORD": {
        "type": SettingType.STRING,
        "category": SettingCategory.LONG_TERM_STORAGE,
        "subcategory": "connection",
        "description": "settingDesc.POSTGRES_PASSWORD",
        "default": "postgres",
        "is_sensitive": True,
        "depends_on": "ENABLE_POSTGRES_STORAGE",
    },
    "POSTGRES_DB": {
        "type": SettingType.STRING,
        "category": SettingCategory.LONG_TERM_STORAGE,
        "subcategory": "connection",
        "description": "settingDesc.POSTGRES_DB",
        "default": "langgraph",
        "depends_on": "ENABLE_POSTGRES_STORAGE",
    },
    "POSTGRES_POOL_MIN_SIZE": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.LONG_TERM_STORAGE,
        "subcategory": "pool",
        "description": "settingDesc.POSTGRES_POOL_MIN_SIZE",
        "default": 2,
        "depends_on": "ENABLE_POSTGRES_STORAGE",
    },
    "POSTGRES_POOL_MAX_SIZE": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.LONG_TERM_STORAGE,
        "subcategory": "pool",
        "description": "settingDesc.POSTGRES_POOL_MAX_SIZE",
        "default": 10,
        "depends_on": "ENABLE_POSTGRES_STORAGE",
    },
    # ============================================
    # Checkpoint Backend Settings
    # ============================================
    "CHECKPOINT_BACKEND": {
        "type": SettingType.SELECT,
        "category": SettingCategory.CHECKPOINT,
        "subcategory": "general",
        "description": "settingDesc.CHECKPOINT_BACKEND",
        "default": "mongodb",
        "options": ["mongodb", "postgres"],
        "frontend_visible": True,
    },
    "CHECKPOINT_PG_HOST": {
        "type": SettingType.STRING,
        "category": SettingCategory.CHECKPOINT,
        "subcategory": "postgres",
        "description": "settingDesc.CHECKPOINT_PG_HOST",
        "default": "",
        "depends_on": {"key": "CHECKPOINT_BACKEND", "value": "postgres"},
    },
    "CHECKPOINT_PG_PORT": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.CHECKPOINT,
        "subcategory": "postgres",
        "description": "settingDesc.CHECKPOINT_PG_PORT",
        "default": 5432,
        "depends_on": {"key": "CHECKPOINT_BACKEND", "value": "postgres"},
    },
    "CHECKPOINT_PG_USER": {
        "type": SettingType.STRING,
        "category": SettingCategory.CHECKPOINT,
        "subcategory": "postgres",
        "description": "settingDesc.CHECKPOINT_PG_USER",
        "default": "",
        "depends_on": {"key": "CHECKPOINT_BACKEND", "value": "postgres"},
    },
    "CHECKPOINT_PG_PASSWORD": {
        "type": SettingType.STRING,
        "category": SettingCategory.CHECKPOINT,
        "subcategory": "postgres",
        "description": "settingDesc.CHECKPOINT_PG_PASSWORD",
        "default": "",
        "is_sensitive": True,
        "depends_on": {"key": "CHECKPOINT_BACKEND", "value": "postgres"},
    },
    "CHECKPOINT_PG_DB": {
        "type": SettingType.STRING,
        "category": SettingCategory.CHECKPOINT,
        "subcategory": "postgres",
        "description": "settingDesc.CHECKPOINT_PG_DB",
        "default": "",
        "depends_on": {"key": "CHECKPOINT_BACKEND", "value": "postgres"},
    },
    "CHECKPOINT_PG_POOL_MIN_SIZE": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.CHECKPOINT,
        "subcategory": "postgres",
        "description": "settingDesc.CHECKPOINT_PG_POOL_MIN_SIZE",
        "default": 2,
        "depends_on": {"key": "CHECKPOINT_BACKEND", "value": "postgres"},
    },
    "CHECKPOINT_PG_POOL_MAX_SIZE": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.CHECKPOINT,
        "subcategory": "postgres",
        "description": "settingDesc.CHECKPOINT_PG_POOL_MAX_SIZE",
        "default": 10,
        "depends_on": {"key": "CHECKPOINT_BACKEND", "value": "postgres"},
    },
    # ============================================
    # User Management Settings
    # ============================================
    "DEFAULT_USER_ROLE": {
        "type": SettingType.STRING,
        "category": SettingCategory.USER,
        "subcategory": "registration",
        "description": "settingDesc.DEFAULT_USER_ROLE",
        "default": "user",
    },
    "ENABLE_REGISTRATION": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.USER,
        "subcategory": "registration",
        "description": "settingDesc.ENABLE_REGISTRATION",
        "default": True,
        "frontend_visible": True,
    },
    # ============================================
    # OAuth Settings
    # ============================================
    "OAUTH_GOOGLE_ENABLED": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.OAUTH,
        "subcategory": "google",
        "description": "settingDesc.OAUTH_GOOGLE_ENABLED",
        "default": False,
        "frontend_visible": True,
    },
    "OAUTH_GOOGLE_CLIENT_ID": {
        "type": SettingType.STRING,
        "category": SettingCategory.OAUTH,
        "subcategory": "google",
        "description": "settingDesc.OAUTH_GOOGLE_CLIENT_ID",
        "default": "",
        "depends_on": "OAUTH_GOOGLE_ENABLED",
    },
    "OAUTH_GOOGLE_CLIENT_SECRET": {
        "type": SettingType.STRING,
        "category": SettingCategory.OAUTH,
        "subcategory": "google",
        "description": "settingDesc.OAUTH_GOOGLE_CLIENT_SECRET",
        "default": "",
        "depends_on": "OAUTH_GOOGLE_ENABLED",
        "is_sensitive": True,
    },
    "OAUTH_GITHUB_ENABLED": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.OAUTH,
        "subcategory": "github",
        "description": "settingDesc.OAUTH_GITHUB_ENABLED",
        "default": False,
        "frontend_visible": True,
    },
    "OAUTH_GITHUB_CLIENT_ID": {
        "type": SettingType.STRING,
        "category": SettingCategory.OAUTH,
        "subcategory": "github",
        "description": "settingDesc.OAUTH_GITHUB_CLIENT_ID",
        "default": "",
        "depends_on": "OAUTH_GITHUB_ENABLED",
    },
    "OAUTH_GITHUB_CLIENT_SECRET": {
        "type": SettingType.STRING,
        "category": SettingCategory.OAUTH,
        "subcategory": "github",
        "description": "settingDesc.OAUTH_GITHUB_CLIENT_SECRET",
        "default": "",
        "depends_on": "OAUTH_GOOGLE_ENABLED",
        "is_sensitive": True,
    },
    "OAUTH_APPLE_ENABLED": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.OAUTH,
        "subcategory": "apple",
        "description": "settingDesc.OAUTH_APPLE_ENABLED",
        "default": False,
        "frontend_visible": True,
    },
    "OAUTH_APPLE_CLIENT_ID": {
        "type": SettingType.STRING,
        "category": SettingCategory.OAUTH,
        "subcategory": "apple",
        "description": "settingDesc.OAUTH_APPLE_CLIENT_ID",
        "default": "",
        "depends_on": "OAUTH_APPLE_ENABLED",
    },
    "OAUTH_APPLE_CLIENT_SECRET": {
        "type": SettingType.STRING,
        "category": SettingCategory.OAUTH,
        "subcategory": "apple",
        "description": "settingDesc.OAUTH_APPLE_CLIENT_SECRET",
        "default": "",
        "depends_on": "OAUTH_APPLE_ENABLED",
        "is_sensitive": True,
    },
    "OAUTH_APPLE_TEAM_ID": {
        "type": SettingType.STRING,
        "category": SettingCategory.OAUTH,
        "subcategory": "apple",
        "description": "settingDesc.OAUTH_APPLE_TEAM_ID",
        "default": "",
        "depends_on": "OAUTH_APPLE_ENABLED",
    },
    "OAUTH_APPLE_KEY_ID": {
        "type": SettingType.STRING,
        "category": SettingCategory.OAUTH,
        "subcategory": "apple",
        "description": "settingDesc.OAUTH_APPLE_KEY_ID",
        "default": "",
        "depends_on": "OAUTH_APPLE_ENABLED",
    },
    # ============================================
    # Memory Settings (Master Switch)
    # ============================================
    "ENABLE_MEMORY": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.MEMORY,
        "subcategory": "general",
        "description": "settingDesc.ENABLE_MEMORY",
        "default": False,
        "frontend_visible": True,
    },
    # ============================================
    # Memory Embedding Settings
    # ============================================
    "NATIVE_MEMORY_EMBEDDING_API_BASE": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_EMBEDDING,
        "subcategory": "api",
        "description": "settingDesc.NATIVE_MEMORY_EMBEDDING_API_BASE",
        "default": "",
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_EMBEDDING_API_KEY": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_EMBEDDING,
        "subcategory": "api",
        "description": "settingDesc.NATIVE_MEMORY_EMBEDDING_API_KEY",
        "default": "",
        "is_sensitive": True,
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_EMBEDDING_MODEL": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_EMBEDDING,
        "subcategory": "api",
        "description": "settingDesc.NATIVE_MEMORY_EMBEDDING_MODEL",
        "default": "text-embedding-3-small",
        "depends_on": "ENABLE_MEMORY",
    },
    # ============================================
    # Memory Search & Index Settings
    # ============================================
    "NATIVE_MEMORY_INDEX_ENABLED": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "index",
        "description": "settingDesc.NATIVE_MEMORY_INDEX_ENABLED",
        "default": True,
        "depends_on": "ENABLE_MEMORY",
        "frontend_visible": True,
    },
    "NATIVE_MEMORY_INDEX_CACHE_TTL": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "index",
        "description": "settingDesc.NATIVE_MEMORY_INDEX_CACHE_TTL",
        "default": 300,
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_RERANK_MODEL": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "rerank",
        "description": "settingDesc.NATIVE_MEMORY_RERANK_MODEL",
        "default": "",
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_RERANK_API_BASE": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "rerank",
        "description": "settingDesc.NATIVE_MEMORY_RERANK_API_BASE",
        "default": "",
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_RERANK_API_KEY": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "rerank",
        "description": "settingDesc.NATIVE_MEMORY_RERANK_API_KEY",
        "default": "",
        "is_sensitive": True,
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_APPEND_MAX_DETAILS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "limits",
        "description": "settingDesc.NATIVE_MEMORY_APPEND_MAX_DETAILS",
        "default": 8,
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_MAX_TOKENS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "limits",
        "description": "settingDesc.NATIVE_MEMORY_MAX_TOKENS",
        "default": 2000,
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_INLINE_CONTENT_MAX_CHARS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "limits",
        "description": "settingDesc.NATIVE_MEMORY_INLINE_CONTENT_MAX_CHARS",
        "default": 1200,
        "depends_on": "ENABLE_MEMORY",
    },
    # ============================================
    # Memory Storage & Policy Settings
    # ============================================
    "NATIVE_MEMORY_MODEL": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_STORAGE,
        "subcategory": "llm",
        "description": "settingDesc.NATIVE_MEMORY_MODEL",
        "default": "",
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_API_BASE": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_STORAGE,
        "subcategory": "llm",
        "description": "settingDesc.NATIVE_MEMORY_API_BASE",
        "default": "",
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_API_KEY": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_STORAGE,
        "subcategory": "llm",
        "description": "settingDesc.NATIVE_MEMORY_API_KEY",
        "default": "",
        "is_sensitive": True,
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_STORE_NAMESPACE": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_STORAGE,
        "subcategory": "policy",
        "description": "settingDesc.NATIVE_MEMORY_STORE_NAMESPACE",
        "default": "memories",
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_STALENESS_DAYS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_STORAGE,
        "subcategory": "policy",
        "description": "settingDesc.NATIVE_MEMORY_STALENESS_DAYS",
        "default": 30,
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_PRUNE_THRESHOLD": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_STORAGE,
        "subcategory": "policy",
        "description": "settingDesc.NATIVE_MEMORY_PRUNE_THRESHOLD",
        "default": 90,
        "depends_on": "ENABLE_MEMORY",
    },
}
